#!/bin/bash

echo polarityReview: Classify
echo 
./mdl-classify -i 1 examples/polarityReview/polarityReview_test models/polarityReview-50.mod results/polarityReview-50.res


echo polarityReview: Performance
./mdl-performance examples/polarityReview/polarityReview_goldstandard results/polarityReview-50.res > performance/polarityReview-50.txt

echo polarityReview: Finished!
echo -------------------------






echo SMSSpamCollection: Classify
echo 
./mdl-classify -i 2 examples/SMSSpamCollection/SMSSpamCollection_test models/SMSSpamCollection-50.mod results/SMSSpamCollection-50.res


echo SMSSpamCollection: Performance
./mdl-performance examples/SMSSpamCollection/SMSSpamCollection_goldstandard results/SMSSpamCollection-50.res > performance/SMSSpamCollection-50.txt


echo SMSSpamCollection: Finished!
echo ----------------------------






echo Reuters: Classify
echo 
./mdl-classify -i 3 examples/libsvm_format/reuters_test.libsvm models/mdl_reuters.mod results/mdlCF_reuters.res


echo Reuters: Performance
./mdl-performance examples/libsvm_format/reuters_test.libsvm results/mdlCF_reuters.res > performance/mdlCF_reuters.txt


echo Reuters: Finished!
echo ----------------------------



